[package]
name = "cfonts"
version = "4.0.0"
edition = "2024"
authors = ["Dominik Wilkowski <Hi@Dominik-Wilkowski.com>"]
license = "GPL-3.0-or-later"
description = "Sexy ANSI fonts for the console"
homepage = "https://github.com/dominikwilkowski/cfonts"
repository = "https://github.com/dominikwilkowski/cfonts"
documentation = "https://docs.rs/cfonts/"
keywords = ["fonts", "color", "console", "ascii", "ANSI"]
categories = ["command-line-interface", "command-line-utilities", "graphics"]

[dependencies]
cfonts-macros = { path = "macros", version = "=4.0.0" }
ratatui = { version = "0.30", optional = true }
terminal_size = "0.4"

[features]
ratatui = ["dep:ratatui"]

[[example]]
name = "ratatui"
required-features = ["ratatui"]

[workspace]
members = [".", "macros"]
default-members = ["."]
resolver = "3"
