[package]
name = "cfonts"
description = "Sexy ANSI fonts for the console"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
documentation = "https://docs.rs/cfonts/"
keywords = ["fonts", "color", "console", "ascii", "ANSI"]
categories = ["command-line-interface", "command-line-utilities", "graphics"]
include = [
	"src/**",
	"!**/.DS_Store",
	"examples/**",
	"Cargo.toml",
	"../../README.md",
	"../../LICENSE",
]

[dependencies]
cfonts-macros = { path = "../macros", version = "=4.0.0" }
dioxus = { version = "0.7", optional = true, default-features = false, features = [
	"html",
	"macro",
	"signals",
] }
leptos = { version = "0.8", optional = true, default-features = false }
ratatui = { version = "0.30", optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
terminal_size = "0.4"

[dev-dependencies]
temp-env = "0.3"

[features]
dioxus = ["dep:dioxus"]
leptos = ["dep:leptos"]
ratatui = ["dep:ratatui"]

[[example]]
name = "ratatui"
required-features = ["ratatui"]
