[package]
name = "cfonts-wasm"
version.workspace = true
edition.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cfonts = { path = "../cfonts" }
serde = { version = "1", features = ["derive"] }
tsify = { version = "0.5", features = ["js"] }
wasm-bindgen = "0.2"

[dev-dependencies]
wasm-bindgen-test = "0.3"
