[package]
name = "cfonts-wasm"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cfonts = { path = "../.." }
serde = { version = "1", features = ["derive"] }
tsify = { version = "0.5", features = ["js"] }
wasm-bindgen = "0.2"

[dev-dependencies]
wasm-bindgen-test = "0.3"
