name: Testing

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - "released"
  pull_request:
    branches:
      - "released"

jobs:
  lint:
    strategy:
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          args: --manifest-path ./rust/Cargo.toml

      - name: Tree files
        run: |
          sudo apt-get -y install tree & which tree
          tree -I "node_modules*|.git*"

      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt

      - name: Annotate commit with clippy warnings
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    env:
      OS: ${{ matrix.OS }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Run build
        run: cargo build --release --verbose

      - name: Run cargo tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-fail-fast -- --nocapture

  # ***********
  # COVERAGE
  # ***********
  coverage:
    needs: test
    strategy:
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install Rust
        run: rustup toolchain install stable --component llvm-tools-preview

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Generate code coverage
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info

      - name: Print last few lines of lcov.info
        run: tail ./lcov.info

      - name: Upload to coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./lcov.info
          flag-name: rust
          parallel: true
        env:
          NODE_COVERALLS_DEBUG: 1

  # ***********
  # COVERAGE - finalizing
  # ***********
  coverage-finish:
    needs: coverage
    strategy:
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Coveralls Parallel Build Finished
        uses: coverallsapp/github-action@v1.1.0
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
        env:
          NODE_COVERALLS_DEBUG: 1
